

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "9474:7474"
      - "9687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - neo4j_data:/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "8333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  neo4j_data:
  qdrant_data: